name: Convert CSV to JSON

on:
  push:
    paths:
      - guests.csv

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Convert CSV to JSON
        run: |
          node convert.js

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add guests.json
          git commit -m "Mise à jour guests.json auto"
          git push
